name: Run Rest Assured Tests Every 4 Hours

on:
    workflow_dispatch:       # Allows manual triggering from GitHub UI
    schedule:
      - cron: '*/10 * * * *'   # Every 10 minutes UTC (also every 10 minutes IST)
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout base framework dependency
        uses: actions/checkout@v3
        with:
          repository: 360f-tech/Core_360f_API_Automation
          path: 360f-tech

          token: ${{ secrets.PAT }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4

        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install base framework to local Maven repository
        run: |
          cd 360f-tech
          mvn clean install -DskipTests
      - name: Build with Maven and execute API scripts
        run: mvn clean install test -DtestSuite="test.xml" --file pom.xml

        continue-on-error: true

      - name: Upload Extent Reports to Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Custom-reports
          path: test-output/react-report